# Set the application name
spring.application.name=discovery-server

# Set the server port (8761 is the standard for Eureka)
server.port=8761

# Configuration for Eureka Client (which is part of the server)
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

#register-with-eureka=false: "Do not try to register yourself with a discovery server." (Because you are the discovery server).
#fetch-registry=false: "Do not try to fetch the registry of services from another server." (Because you are the source of truth).